# Generated by Django 4.0.3 on 2022-05-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_img_product_product_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
