# Generated by Django 4.0.3 on 2022-05-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=10)),
                ('product_url', models.CharField(max_length=300)),
                ('product_img', models.CharField(max_length=300)),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile')),
            ],
        ),
    ]
