# Generated by Django 4.0.3 on 2022-05-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='saved_by',
        ),
        migrations.CreateModel(
            name='FavList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favlist_name', models.CharField(default='My Favorites', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='saved_by',
            field=models.ManyToManyField(blank=True, to='favorites.favlist'),
        ),
    ]
