# Generated by Django 4.0.3 on 2022-05-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_product_saved_by_favlist_product_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='saved_by',
        ),
        migrations.DeleteModel(
            name='FavList',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
